export const Strings = {
    all: "All",
    login: "Login",
    logOut: "Log out",
    email: "Email",
    createAccount: "Create a account",
    signUp: "Sign up",
    totalGoals: "Total goals",
    mediumPriorityGoals: "Medium priority goals",
    lowPriorityGoals: "Low priority goals",
    highPriorityGoals: "High priority goals",
    anaylsis: "Analysis",
    emailNotRegister: "email not register",
    totalTargetDays: "Total target days",
    archivedGoalsDays: "Archived goals days",
    nonArchivedDays: "Non archived days",
    attendation: "Attendation",
    greenBackgroundColorIndicateThatYouHaveCompletedThatDay: "Green background color indicate that you have completed that day",
    redBackgroundColorIndicateThatYouHaveNotCompletedThatDay: "Red background color indicate that you have not completed that day",
    overallProgress: "Overall progress",
    goalHistory: "Goal history",
    remainingDays: "Remaining days",
    backToLogin: "Back to login",
    goals: "Goals",
    pleaseSelectedPreviousDateFromToday: "Please selected previous from today",
    incomplted: "InCompleted",
    notCompleted: "Not completed",
    update: "Update",
    completed: "Completed",
    areYouSureWantToLogOut: "Are you sure want to log out ?",
    emailAlreadyRegister: "email already register",
    home: "Home",
    goalsProcess: "Goals process",
    areYouWantToDeleteThisGoal: "Are you sure want to delete this goal?",
    process: "Process",
    loginEmail: "Login email",
    actions: "Actions",
    viewDailyProcess: "View daily process",
    delete: "Delete",
    noGoalAdded: "No goals found",
    manage: "Manage",
    edit: "Edit",
    todayAsCompleted: "Today as completed",
    dashboard: "Dashboard",
    yourGoalSuccussFullyUpdated: "Your goal successfully updated",
    yourGoalSuccessFullyAdded: "Your goals successfully added",
    high: "High",
    low: "Low",
    medium: "Medium",
    addGoals: "Add Goal",
    ok: "Ok",
    name: "Name",
    goToGoals: "Go to goals",
    cancel: "Cancel",
    goalNotFound: "Goal details not found",
    enterAGoalName: "Enter a goal name",
    startDate: "Start date",
    updateDailyProgress: "Update daily progress",
    selectStartDate: "Select start date",
    dueDate: "Due date",
    updateGoal: "Update goal",
    selectDueDate: "Select due date",
    priority: "Priority",
    archiveSteps: "Archive steps",
    selectAPriority: "Select a priority",
    pleaseEnterAGoalName: "Please enter a goal name",
    pleaseSelectStartDate: "Please select a start date",
    pleaseSelectEndDate: "Please select a end date",
    pleaseSelectAPriority: "Please select a priority",
    pleaseWait: "Please wait...",
    pleaseEnterEmail: "Please enter email",
    pleaseEnterValidEmail: "Please enter valid email",
    query: "query"
}